// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtelRez.DAL.DbContexts;

#nullable disable

namespace OtelRez.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241208143421_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OtelRez.Entity.Entities.Concrete.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("OtelRez.Entity.Entities.Concrete.Oda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Fiyat")
                        .HasColumnType("int");

                    b.Property<bool>("Musait")
                        .HasColumnType("bit");

                    b.Property<string>("OdaNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OdaTurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OdaTurId");

                    b.ToTable("Odalar");
                });

            modelBuilder.Entity("OtelRez.Entity.Entities.Concrete.OdaTur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Kapasite")
                        .HasColumnType("smallint");

                    b.Property<string>("TurAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurDetay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OdaTurleri");
                });

            modelBuilder.Entity("OtelRez.Entity.Entities.Concrete.PersonelMeslek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Maas")
                        .HasColumnType("int");

                    b.Property<string>("Meslek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonelMeslekler");
                });

            modelBuilder.Entity("OtelRez.Entity.Entities.Concrete.Rezervasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Cikis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Giris")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("OdaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("OdaId")
                        .IsUnique();

                    b.ToTable("Rezervasyonlar");
                });

            modelBuilder.Entity("OtinternalEntity.Entitieste.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IzinHakki")
                        .HasColumnType("int");

                    b.Property<int>("PersonelMeslekId")
                        .HasColumnType("int");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonelMeslekId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("OtelRez.Entity.Entities.Concrete.Oda", b =>
                {
                    b.HasOne("OtelRez.Entity.Entities.Concrete.OdaTur", "OdaTur")
                        .WithMany("Odalar")
                        .HasForeignKey("OdaTurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OdaTur");
                });

            modelBuilder.Entity("OtelRez.Entity.Entities.Concrete.Rezervasyon", b =>
                {
                    b.HasOne("OtelRez.Entity.Entities.Concrete.Kullanici", "Kullanici")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtelRez.Entity.Entities.Concrete.Oda", "Oda")
                        .WithOne("Rezervasyon")
                        .HasForeignKey("OtelRez.Entity.Entities.Concrete.Rezervasyon", "OdaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Oda");
                });

            modelBuilder.Entity("OtinternalEntity.Entitieste.Personel", b =>
                {
                    b.HasOne("OtelRez.Entity.Entities.Concrete.PersonelMeslek", "PersonelMeslek")
                        .WithMany("Personeller")
                        .HasForeignKey("PersonelMeslekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonelMeslek");
                });

            modelBuilder.Entity("OtelRez.Entity.Entities.Concrete.Kullanici", b =>
                {
                    b.Navigation("Rezervasyonlar");
                });

            modelBuilder.Entity("OtelRez.Entity.Entities.Concrete.Oda", b =>
                {
                    b.Navigation("Rezervasyon")
                        .IsRequired();
                });

            modelBuilder.Entity("OtelRez.Entity.Entities.Concrete.OdaTur", b =>
                {
                    b.Navigation("Odalar");
                });

            modelBuilder.Entity("OtelRez.Entity.Entities.Concrete.PersonelMeslek", b =>
                {
                    b.Navigation("Personeller");
                });
#pragma warning restore 612, 618
        }
    }
}
